debezium.sink.type=redis
debezium.sink.redis.address=redis:6379

debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=postgres
debezium.source.database.dbname=electric-avenue
debezium.source.database.server.name=db
debezium.source.topic.prefix=db
debezium.source.plugin.name=pgoutput
debezium.source.table.include.list=public.products,public.product_variants,public.product_images,public.product_attribute_values,public.variant_attribute_values

debezium.format.key=json
debezium.format.value=json
debezium.format.key.schemas.enable=false
debezium.format.value.schemas.enable=false

debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.offset.flush.interval.ms=1000